# Generated by Django 4.1.7 on 2023-03-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERNAME', models.CharField(max_length=50)),
                ('PASSWORD', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERNAME', models.CharField(max_length=50)),
                ('EMAIL', models.CharField(max_length=50)),
                ('PHONENUMBER', models.IntegerField()),
                ('PASSWORD', models.IntegerField()),
                ('CONFIRMPASSWORD', models.IntegerField()),
            ],
        ),
    ]
