# Generated by Django 4.1.7 on 2023-05-17 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='ADDRESS',
            new_name='PLACE',
        ),
    ]
