# Generated by Django 4.1.7 on 2023-05-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0005_booking_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='buss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=50)),
                ('PHONENUMBER', models.IntegerField()),
                ('PLACE', models.CharField(max_length=50)),
                ('PEOPLE', models.IntegerField()),
                ('PAYMENT', models.IntegerField()),
            ],
        ),
    ]
