# Generated by Django 4.1.7 on 2023-05-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0006_buss'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='PROOF',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
