# Generated by Django 4.1.7 on 2023-06-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0007_booking_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='AMOUNT',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
