# Generated by Django 4.1.7 on 2023-06-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0008_booking_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buss',
            name='PAYMENT',
        ),
        migrations.RemoveField(
            model_name='buss',
            name='PLACE',
        ),
        migrations.AddField(
            model_name='buss',
            name='FROM',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buss',
            name='TO',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
