# Generated by Django 4.1.7 on 2023-07-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0009_remove_buss_payment_remove_buss_place_buss_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buss',
            name='AMOUNT',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
